In [1]:
import numpy as np
import pandas as pd


In [2]:
from sklearn.datasets import *
data = load_iris()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = pd.Series(data.target)

In [3]:
# Standrize
from sklearn.preprocessing import StandardScaler
feat_names = data.feature_names
scaler = StandardScaler()
df[feat_names]=scaler.fit_transform(df[feat_names])

In [4]:
cov = np.cov(df[feat_names].T,bias=True)
df[feat_names].cov()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.006711         -0.118359           0.877604   
sepal width (cm)           -0.118359          1.006711          -0.431316   
petal length (cm)           0.877604         -0.431316           1.006711   
petal width (cm)            0.823431         -0.368583           0.969328   

                   petal width (cm)  
sepal length (cm)          0.823431  
sepal width (cm)          -0.368583  
petal length (cm)          0.969328  
petal width (cm)           1.006711

In [5]:
lambda_v,vector = np.linalg.eig(cov)
print(lambda_v)
print(vector)


[2.91849782 0.91403047 0.14675688 0.02071484]
[[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


In [6]:
# projecting
df[feat_names]=df[feat_names].dot(vector)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0          -2.264703         -0.480027          -0.127706          0.024168   
1          -2.080961          0.674134          -0.234609          0.103007   
2          -2.364229          0.341908           0.044201          0.028377   
3          -2.299384          0.597395           0.091290         -0.065956   
4          -2.389842         -0.646835           0.015738         -0.035923   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [7]:
# variances
var = []
for i in range(len(lambda_v)):
    var.append(lambda_v[i]/np.sum(lambda_v))

var

[0.7296244541329989,
 0.2285076178670175,
 0.03668921889282878,
 0.005178709107154814]

In [8]:
np.cumsum(var)

array([0.72962445, 0.95813207, 0.99482129, 1.        ])

In [10]:
from sklearn.linear_model import LogisticRegression
df2 = df.iloc[:,0:2]


df3 = df.iloc[:, 0:3]

#modeMod1
lr1 = LogisticRegression()
lr1.fit(df[feat_names], df["target"])
print("all data: ", lr1.score(df[feat_names], df["target"]))

#modeMod1
lr2 = LogisticRegression()
lr2.fit(df3, df["target"])
print("3 PCs:   ", lr2.score(df3, df["target"]))

#modeMod1
lr3 = LogisticRegression()
lr3.fit(df2, df["target"])
print("2 PCs:    ", lr3.score(df2, df["target"]))

all data:  0.9733333333333334
3 PCs:    0.9733333333333334
2 PCs:     0.9333333333333333
